"""Init

Revision ID: 20d3f0fbd778
Revises: 
Create Date: 2025-02-01 14:21:39.282782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d3f0fbd778'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carditem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('card_name', sa.String(length=255), nullable=True),
    sa.Column('team', sa.String(length=255), nullable=True),
    sa.Column('league', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardpack',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardxpack',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=True),
    sa.Column('user_card_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=25), nullable=True),
    sa.Column('last_free', sa.BigInteger(), nullable=True),
    sa.Column('free_quant', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('curr_casino', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packbattle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('quant', sa.Integer(), nullable=True),
    sa.Column('owner', sa.BigInteger(), nullable=True),
    sa.Column('owner_msg_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_username', sa.String(length=255), nullable=True),
    sa.Column('owner_points', sa.Integer(), nullable=True),
    sa.Column('owner_ts', sa.BigInteger(), nullable=True),
    sa.Column('owner_ready', sa.Integer(), nullable=True),
    sa.Column('target', sa.BigInteger(), nullable=True),
    sa.Column('target_msg_id', sa.BigInteger(), nullable=True),
    sa.Column('target_username', sa.String(length=255), nullable=True),
    sa.Column('target_points', sa.Integer(), nullable=True),
    sa.Column('target_ts', sa.BigInteger(), nullable=True),
    sa.Column('target_ready', sa.Integer(), nullable=True),
    sa.Column('winner', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payitem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=25), nullable=True),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penalty',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('kind', sa.String(length=25), nullable=True),
    sa.Column('owner', sa.BigInteger(), nullable=True),
    sa.Column('owner_msg_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_username', sa.String(length=255), nullable=True),
    sa.Column('owner_score', sa.Integer(), nullable=True),
    sa.Column('owner_txt', sa.String(length=15), nullable=True),
    sa.Column('owner_card_id', sa.Integer(), nullable=True),
    sa.Column('target', sa.BigInteger(), nullable=True),
    sa.Column('target_msg_id', sa.BigInteger(), nullable=True),
    sa.Column('target_username', sa.String(length=255), nullable=True),
    sa.Column('target_score', sa.Integer(), nullable=True),
    sa.Column('target_txt', sa.String(length=15), nullable=True),
    sa.Column('target_card_id', sa.Integer(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('turn_user_id', sa.BigInteger(), nullable=True),
    sa.Column('kicker', sa.BigInteger(), nullable=True),
    sa.Column('kicker_pick', sa.Integer(), nullable=True),
    sa.Column('keeper', sa.BigInteger(), nullable=True),
    sa.Column('last_action', sa.BigInteger(), nullable=True),
    sa.Column('winner', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('access_minigame', sa.String(length=20), nullable=True),
    sa.Column('game_pass', sa.String(length=10), nullable=True),
    sa.Column('pass_ts', sa.BigInteger(), nullable=True),
    sa.Column('pass_until', sa.String(length=50), nullable=True),
    sa.Column('card_quants', sa.BigInteger(), nullable=True),
    sa.Column('rating', sa.BigInteger(), nullable=True),
    sa.Column('season_rating', sa.BigInteger(), nullable=True),
    sa.Column('prev_season_rating', sa.BigInteger(), nullable=True),
    sa.Column('season_penalty', sa.BigInteger(), nullable=True),
    sa.Column('prev_season_penalty', sa.BigInteger(), nullable=True),
    sa.Column('penalty_queue', sa.Integer(), nullable=True),
    sa.Column('pen_wins', sa.Integer(), nullable=True),
    sa.Column('pen_loses', sa.Integer(), nullable=True),
    sa.Column('last_open', sa.BigInteger(), nullable=True),
    sa.Column('open_count', sa.Integer(), nullable=True),
    sa.Column('transactions', sa.BigInteger(), nullable=True),
    sa.Column('lucky_quants', sa.Integer(), nullable=True),
    sa.Column('last_lucky', sa.BigInteger(), nullable=True),
    sa.Column('lucky_shots_plus', sa.Integer(), nullable=True),
    sa.Column('joined_at_ts', sa.BigInteger(), nullable=True),
    sa.Column('joined_at_txt', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=25), nullable=True),
    sa.Column('ban_status', sa.String(length=20), nullable=True),
    sa.Column('trade_count', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playerpick',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('card_one', sa.Integer(), nullable=True),
    sa.Column('card_two', sa.Integer(), nullable=True),
    sa.Column('card_three', sa.Integer(), nullable=True),
    sa.Column('card_pick', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promocode',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('promo', sa.Text(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=True),
    sa.Column('quant', sa.Integer(), nullable=True),
    sa.Column('users', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promouser',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('promo_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('season',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.String(length=25), nullable=True),
    sa.Column('rating', sa.BigInteger(), nullable=True),
    sa.Column('date_str', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('quant', sa.Integer(), nullable=True),
    sa.Column('owner', sa.BigInteger(), nullable=True),
    sa.Column('owner_username', sa.String(length=255), nullable=True),
    sa.Column('owner_card_id', sa.Integer(), nullable=True),
    sa.Column('target', sa.BigInteger(), nullable=True),
    sa.Column('target_username', sa.String(length=255), nullable=True),
    sa.Column('target_card_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tradecard',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.BigInteger(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('user_card_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userpacks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('five_pack', sa.Integer(), nullable=True),
    sa.Column('ten_pack', sa.Integer(), nullable=True),
    sa.Column('twenty_pack', sa.Integer(), nullable=True),
    sa.Column('thirty_pack', sa.Integer(), nullable=True),
    sa.Column('player_pick', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usertrade',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_x_user', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usercard',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('card_rarity', sa.String(length=20), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('duplicate', sa.Integer(), nullable=True),
    sa.Column('tradeble', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['carditem.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usercard')
    op.drop_table('usertrade')
    op.drop_table('userpacks')
    op.drop_table('tradecard')
    op.drop_table('trade')
    op.drop_table('season')
    op.drop_table('promouser')
    op.drop_table('promocode')
    op.drop_table('playerpick')
    op.drop_table('player')
    op.drop_table('penalty')
    op.drop_table('payitem')
    op.drop_table('packbattle')
    op.drop_table('games')
    op.drop_table('cardxpack')
    op.drop_table('cardpack')
    op.drop_table('carditem')
    # ### end Alembic commands ###
