"""Add rating to player. Add position, attack, defense rates to CardItem

Revision ID: 24bea688600f
Revises: 20d3f0fbd778
Create Date: 2025-02-01 18:13:39.143283

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24bea688600f"
down_revision: Union[str, None] = "20d3f0fbd778"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    position_type = sa.dialects.postgresql.ENUM(
        "GOALKEEPER", "DEFENDER", "MIDFIELDER", "FORWARD", name="cardpositiontype"
    )
    position_type.create(op.get_bind())
    op.add_column(
        "carditem",
        sa.Column(
            "position",
            sa.Enum(
                "GOALKEEPER",
                "DEFENDER",
                "MIDFIELDER",
                "FORWARD",
                name="cardpositiontype",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "carditem", sa.Column("attack_rate", sa.Integer(), default=0, nullable=True)
    )
    op.add_column(
        "carditem", sa.Column("defense_rate", sa.Integer(), default=0, nullable=True)
    )
    op.add_column(
        "carditem", sa.Column("general_rate", sa.Integer(), default=0, nullable=True)
    )
    op.alter_column(
        "player",
        "rating",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "player",
        "rating",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    op.drop_column("carditem", "general_rate")
    op.drop_column("carditem", "defense_rate")
    op.drop_column("carditem", "attack_rate")
    op.drop_column("carditem", "position")
    position_type = sa.dialects.postgresql.ENUM(
        "GOALKEEPER", "DEFENDER", "MIDFIELDER", "FORWARD", name="cardpositiontype"
    )
    position_type.drop(op.get_bind())
    # ### end Alembic commands ###
