"""add_trade_count

Revision ID: 56aae93eb433
Revises: 42ea03b22238
Create Date: 2024-09-25 17:56:54.806357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56aae93eb433'
down_revision: Union[str, None] = '42ea03b22238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('trade_count', sa.BigInteger(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'trade_count')
    # ### end Alembic commands ###
