"""Add type for card battle turn

Revision ID: 8974ef43c685
Revises: c398b3052838
Create Date: 2025-02-04 20:32:00.918192

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8974ef43c685"
down_revision: Union[str, None] = "c398b3052838"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    card_battle_turn_type = sa.dialects.postgresql.ENUM(
        "ATTACK", "DEFENSE", name="cardbattleturntype"
    )
    card_battle_turn_type.create(op.get_bind())
    op.add_column(
        "cardbattleturn",
        sa.Column(
            "type",
            sa.Enum("ATTACK", "DEFENSE", name="cardbattleturntype"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    card_battle_turn_type = sa.dialects.postgresql.ENUM(
        "ATTACK", "DEFENSE", name="cardbattleturntype"
    )
    card_battle_turn_type.drop(op.get_bind())
    op.drop_column("cardbattleturn", "type")
    # ### end Alembic commands ###
