"""Change CardBattleTurn

Revision ID: aae486047ccb
Revises: 8974ef43c685
Create Date: 2025-02-09 15:54:53.426084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae486047ccb'
down_revision: Union[str, None] = '8974ef43c685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usercardstobattle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_card_id', sa.BigInteger(), nullable=False),
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['battle_id'], ['cardbattle.id'], ),
    sa.ForeignKeyConstraint(['user_card_id'], ['usercard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cardstobattle')
    op.alter_column('cardbattleturn', 'card_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint('cardbattleturn_card_id_fkey', 'cardbattleturn', type_='foreignkey')
    op.create_foreign_key(None, 'cardbattleturn', 'usercardstobattle', ['card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cardbattleturn', type_='foreignkey')
    op.create_foreign_key('cardbattleturn_card_id_fkey', 'cardbattleturn', 'usercard', ['card_id'], ['id'])
    op.alter_column('cardbattleturn', 'card_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_table('cardstobattle',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_card_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('battle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['battle_id'], ['cardbattle.id'], name='cardstobattle_battle_id_fkey'),
    sa.ForeignKeyConstraint(['user_card_id'], ['usercard.id'], name='cardstobattle_user_card_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cardstobattle_pkey')
    )
    op.drop_table('usercardstobattle')
    # ### end Alembic commands ###
